In [1]:
%%capture # This removes output

# Installs modules if not yet installed
!pip install yfinance;
!pip install alpha_vantage;

In [28]:
from alpha_vantage.fundamentaldata import FundamentalData
import pandas as pd

In [15]:
apikey = "L1LKAHT1YOU2TNZP"
fd = FundamentalData(key=apikey, output_format='pandas')
df_is,meta_data_is = fd.get_income_statement_annual(symbol='FCN')
df_bs,meta_data_bs = fd.get_balance_sheet_annual(symbol = 'FCN')
df_cf,meta_data_cf = fd.get_cash_flow_annual(symbol = 'FCN')

In [16]:
df_is

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
date,,,,,,,,,,,,,,,,,,,,,
1970-01-01 00:00:00.000000000,2020-12-31,USD,788564000,2461275000,1672711000,1672711000,282663000,488411000,None,547864000,...,32600000,32661000,262446000,51764000,19805000,210682000,245094000,282663000,315324000,210682000
1970-01-01 00:00:00.000000001,2019-12-31,USD,817821000,2352717000,1534896000,1534896000,305595000,504074000,None,553829000,...,30100000,30153000,288450000,71724000,19206000,216726000,223696000,305595000,335748000,216726000
1970-01-01 00:00:00.000000002,2018-12-31,USD,699803000,2027877000,1328074000,1328074000,226005000,465636000,8700000,502013000,...,26200000,31536000,207792000,57181000,36221000,150611000,123009000,226005000,257541000,150611000
1970-01-01 00:00:00.000000003,2017-12-31,USD,592172000,1807732000,1215560000,1215560000,108711000,432013000,14900000,478576000,...,24400000,31177000,87105000,-20857000,25358000,107962000,138626000,108711000,139888000,107962000
1970-01-01 00:00:00.000000004,2016-12-31,USD,599623000,1810394000,1210771000,1210771000,142156000,436716000,17500000,501828000,...,26700000,38700000,127803000,42283000,24819000,85520000,43636000,142156000,180856000,85520000

In [17]:
df_bs

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,...,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding
date,,,,,,,,,,,,,,,,,,,,,
1970-01-01 00:00:00.000000000,2020-12-31,USD,2777363000,1129707000,294953000,294953000,None,982895000,1651465000,101642000,...,None,286131000,286131000,44172000,100861000,1400181000,None,1506271000,345000,34481000
1970-01-01 00:00:00.000000001,2019-12-31,USD,2783142000,1178661000,369373000,369373000,None,1017950000,1678762000,93672000,...,35727000,275609000,275609000,36698000,78124000,1489142000,None,1413453000,374000,37390000
1970-01-01 00:00:00.000000002,2018-12-31,USD,2379121000,965353000,312069000,312069000,None,951216000,1172316000,84577000,...,None,265571000,265571000,44434000,127067000,1348825000,None,1196727000,381000,38147000
1970-01-01 00:00:00.000000003,2017-12-31,USD,2257241000,794179000,189961000,189961000,None,894023000,1204803000,75075000,...,396284000,396284000,396284000,410328000,134187000,1191971000,None,1045774000,377000,37729000
1970-01-01 00:00:00.000000004,2016-12-31,USD,2225368000,783171000,216158000,216158000,None,553515000,1180001000,61856000,...,365528000,365528000,365528000,378455000,100228000,1207358000,None,941001000,420000,42037000

In [18]:
df_cf

,fiscalDateEnding,reportedCurrency,operatingCashflow,paymentsForOperatingActivities,proceedsFromOperatingActivities,changeInOperatingLiabilities,changeInOperatingAssets,depreciationDepletionAndAmortization,capitalExpenditures,changeInReceivables,...,dividendPayoutCommonStock,dividendPayoutPreferredStock,proceedsFromIssuanceOfCommonStock,proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,proceedsFromIssuanceOfPreferredStock,proceedsFromRepurchaseOfEquity,proceedsFromSaleOfTreasuryStock,changeInCashAndCashEquivalents,changeInExchangeRate,netIncome
date,,,,,,,,,,,,,,,,,,,,,
1970-01-01 00:00:00.000000000,2020-12-31,USD,327069000,63827000,None,-8648000,14131000,54201000,34866000,18771000,...,None,None,None,None,None,-348693000,None,-93104000,None,210682000
1970-01-01 00:00:00.000000001,2019-12-31,USD,217886000,53685000,None,15589000,154097000,49867000,42072000,131449000,...,None,None,None,None,None,-96097000,None,53969000,None,216726000
1970-01-01 00:00:00.000000002,2018-12-31,USD,230672000,21687000,None,18000,65305000,39818000,32270000,63047000,...,None,None,None,316250000,None,-14138000,None,122108000,-9789000,150611000
1970-01-01 00:00:00.000000003,2017-12-31,USD,147625000,23285000,None,30232000,35274000,34963000,32004000,35903000,...,None,None,None,None,None,-163994000,None,-26197000,7750000,107962000
1970-01-01 00:00:00.000000004,2016-12-31,USD,233488000,23154000,4800000,25280000,-3776000,38985000,28935000,-6616000,...,None,None,None,None,None,5811000,None,66398000,-11648000,85520000

In [67]:
# Function to convert types
def convert_types(series):
    try:
        return pd.to_datetime(series, errors = 'raise')
    except:
        return pd.to_numeric(series, errors = 'coerce')

df_is_copy = df_is.copy()
df_is_copy.reset_index(inplace = True, drop = True)
df_is_copy = df_is_copy.apply(convert_types, axis = 0)
df_is_copy

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,2020-12-31,NaN,788564000,2461275000,1672711000,1672711000,282663000,488411000,NaN,547864000,...,32600000,32661000,262446000,51764000,19805000,210682000,245094000,282663000,315324000,210682000
1,2019-12-31,NaN,817821000,2352717000,1534896000,1534896000,305595000,504074000,NaN,553829000,...,30100000,30153000,288450000,71724000,19206000,216726000,223696000,305595000,335748000,216726000
2,2018-12-31,NaN,699803000,2027877000,1328074000,1328074000,226005000,465636000,8700000.0,502013000,...,26200000,31536000,207792000,57181000,36221000,150611000,123009000,226005000,257541000,150611000
3,2017-12-31,NaN,592172000,1807732000,1215560000,1215560000,108711000,432013000,14900000.0,478576000,...,24400000,31177000,87105000,-20857000,25358000,107962000,138626000,108711000,139888000,107962000
4,2016-12-31,NaN,599623000,1810394000,1210771000,1210771000,142156000,436716000,17500000.0,501828000,...,26700000,38700000,127803000,42283000,24819000,85520000,43636000,142156000,180856000,85520000

In [68]:
import os
from xlwings.constants import InsertShiftDirection
import xlwings as xw
from datetime import date
import config_data as cfd

model_template = os.path.join(
            os.getcwd(), 'templates\dcf_model_2p_blank.xlsx')

wb = xw.Book(model_template)
asm_sht = wb.sheets['Assumptions']
dcf_sht = wb.sheets['DCF']
fcs_sht = wb.sheets['Forecasts']
is_sht = wb.sheets['IS']
bs_sht = wb.sheets['BS']
cfs_sht = wb.sheets['CFS']
beta_sht = wb.sheets['Beta']
comp_sht = wb.sheets['Comps']

ModuleNotFoundError: No module named 'xlwings'